# golangci-lint configuration for Go training exercises
# Students' code will be checked against these rules

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - solution
    - vendor

linters:
  enable:
    - gofmt          # Check code formatting
    - govet          # Reports suspicious constructs
    - errcheck       # Check error handling
    - staticcheck    # Static analysis checks
    - unused         # Check for unused code
    - gosimple       # Suggest code simplifications
    - ineffassign    # Detect ineffectual assignments
    - typecheck      # Type-check Go code
    - misspell       # Find commonly misspelled English words
    - gocritic       # Comprehensive Go source code linter
    - gocyclo        # Check cyclomatic complexity
    - dupl           # Check for duplicate code
    - gosec          # Security-focused linter
    - unconvert      # Remove unnecessary type conversions

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult  # Allow unnamed return values
      - whyNoLint      # Don't require explanation for nolint

  misspell:
    locale: US

  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec

    # Allow panic in main functions (for educational purposes)
    - text: "not implemented"
      linters:
        - gocritic

  max-issues-per-linter: 50
  max-same-issues: 3

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# Service configuration
service:
  golangci-lint-version: 1.55.2
